onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@yanivjs/yaniv-editor'
  - core-js
  - esbuild
  - unrs-resolver

confirmModulesPurge: false
nodeLinker: hoisted
allowBuilds:
  '@parcel/watcher': true
  '@yanivjs/yaniv-editor': true
  core-js: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@yanivjs/*'
